// ============================================================================
// QFlow FDPE Kernel V1 — 128-entry LUT variant
// Standalone ASIC/VLSI study kernel
//
// Difference from V0:
//   V0: 256-entry exp(-x) LUT, 8-bit index
//   V1: 128-entry exp(-x) LUT, 7-bit index
//
// Function:
//   fidelity_out = f_init * exp_lut[index]
//   Q0.16 × Q0.16 -> Q0.16
//
// Research purpose:
//   Compare V1 against V0 to study LUT-size vs synthesis/PPA tradeoff.
// ============================================================================

`timescale 1ns/1ps

module fdpe_kernel_v1_lut128 #(
    parameter FID_W = 16,
    parameter IDX_W = 7
)(
    input  wire                 clk,
    input  wire                 rst_n,

    input  wire                 start,
    input  wire [FID_W-1:0]      f_init_q016,
    input  wire [IDX_W-1:0]      lut_index,

    output reg                  done,
    output reg  [FID_W-1:0]      fidelity_q016
);

    // 128-entry exp(-x) LUT in Q0.16 format.
    // Generated by:
    //   asic/fdpe_kernel/scripts/generate_fdpe_lut.py
    reg [FID_W-1:0] exp_lut [0:127];

    initial begin
        $readmemh("asic/fdpe_kernel/config/exp_lut_128.hex", exp_lut);
    end

    // Pipeline registers
    reg [FID_W-1:0] f_init_s1;
    reg [FID_W-1:0] exp_s1;
    reg             valid_s1;

    reg [31:0]      mult_s2;
    reg             valid_s2;

    always @(posedge clk) begin
        if (!rst_n) begin
            f_init_s1     <= {FID_W{1'b0}};
            exp_s1        <= {FID_W{1'b0}};
            valid_s1      <= 1'b0;

            mult_s2       <= 32'd0;
            valid_s2      <= 1'b0;

            fidelity_q016 <= {FID_W{1'b0}};
            done          <= 1'b0;
        end else begin
            // Stage 1
            valid_s1  <= start;
            f_init_s1 <= f_init_q016;
            exp_s1    <= exp_lut[lut_index];

            // Stage 2
            valid_s2 <= valid_s1;
            mult_s2  <= f_init_s1 * exp_s1;

            // Output stage
            done <= valid_s2;
            if (valid_s2) begin
                fidelity_q016 <= mult_s2[31:16];
            end
        end
    end

endmodule
